### ISSUE TITLE
Replace usage of `text` attribute of `Message` with `text_markdown_v2` property

### ISSUE THREAD

**Issue by Mroik** [StudentiUniMi/backend#23]
This way if a moderator uses `/warn` with a link to a group it will be shown in the warning message too.
https://github.com/StudentiUniMi/backend/blob/3309f181acc5d9f07ea958037fbae0324241a8dc/telegrambot/handlers/moderation.py#L35
An instance where it could be replaced, ideally we would do it across all the codebase.

**Comment by MarcoBuster** [comment]
I'm ok with this, but if the markdown text is not syntactically correct we need to ensure that the command still gets through

**Comment by MarcoBuster** [comment]
However, across the codebase an important thing to do is to implement i18n on a per-user and per-group basis. I'm not sure if this issue will interfere with the future i18n implementation, just keep in mind that
